# Generated by Django 5.2.8 on 2025-11-07 19:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("ccmc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalWebRTCSession",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("video_call", "Video Call"),
                            ("audio_call", "Audio Call"),
                            ("screen_share", "Screen Share"),
                            ("data_channel", "Data Channel Only"),
                        ],
                        default="video_call",
                        max_length=20,
                    ),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for Peers"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ccmc.messagethread",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical web rtc session",
                "verbose_name_plural": "historical web rtc sessions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WebRTCPeer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        help_text="Unique WebSocket channel ID for this peer",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "peer_role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("viewer", "Viewer"),
                            ("participant", "Participant"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                (
                    "connection_state",
                    models.CharField(
                        choices=[
                            ("connecting", "Connecting"),
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("failed", "Failed"),
                        ],
                        default="connecting",
                        max_length=20,
                    ),
                ),
                ("has_video", models.BooleanField(default=False)),
                ("has_audio", models.BooleanField(default=False)),
                ("has_screen_share", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webrtc_peers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="WebRTCSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("video_call", "Video Call"),
                            ("audio_call", "Audio Call"),
                            ("screen_share", "Screen Share"),
                            ("data_channel", "Data Channel Only"),
                        ],
                        default="video_call",
                        max_length=20,
                    ),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for Peers"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_webrtc_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="webrtc_sessions",
                        through="ccmc.WebRTCPeer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webrtc_sessions",
                        to="ccmc.messagethread",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="webrtcpeer",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peers",
                to="ccmc.webrtcsession",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWebRTCPeer",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "channel_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique WebSocket channel ID for this peer",
                        max_length=255,
                    ),
                ),
                (
                    "peer_role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("viewer", "Viewer"),
                            ("participant", "Participant"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                (
                    "connection_state",
                    models.CharField(
                        choices=[
                            ("connecting", "Connecting"),
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("failed", "Failed"),
                        ],
                        default="connecting",
                        max_length=20,
                    ),
                ),
                ("has_video", models.BooleanField(default=False)),
                ("has_audio", models.BooleanField(default=False)),
                ("has_screen_share", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ccmc.webrtcsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical web rtc peer",
                "verbose_name_plural": "historical web rtc peers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WebRTCSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("offer", "Offer"),
                            ("answer", "Answer"),
                            ("ice_candidate", "ICE Candidate"),
                            ("check", "Peer Check"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "signal_data",
                    models.JSONField(help_text="SDP or ICE candidate data"),
                ),
                ("delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_signals",
                        to="ccmc.webrtcpeer",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="ccmc.webrtcsession",
                    ),
                ),
                (
                    "to_peer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_signals",
                        to="ccmc.webrtcpeer",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="webrtcpeer",
            unique_together={("session", "user")},
        ),
    ]
