# Generated by Django 5.2.8 on 2025-11-08 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ccmc", "0002_historicalwebrtcsession_webrtcpeer_webrtcsession_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalwebrtcsession",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="webrtcsession",
            name="thread",
        ),
    ]
