# Generated by Django 5.2.8 on 2025-11-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccmc", "0003_remove_historicalwebrtcsession_thread_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwebrtcsession",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webrtcsession",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
