# Generated by Django 5.2.8 on 2025-11-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccmc", "0004_historicalwebrtcsession_name_webrtcsession_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwebrtcsession",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="webrtcsession",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
