# Generated by Django 5.2.8 on 2025-11-09 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ccmc", "0005_historicalwebrtcsession_is_default_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="webrtcpeer",
            unique_together=set(),
        ),
    ]
