# Generated by Django 5.2.8 on 2025-11-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccmc", "0006_alter_webrtcpeer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwebrtcpeer",
            name="client_peer_id",
            field=models.CharField(
                blank=True,
                help_text="Client-generated persistent ID for reconnection tracking",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="webrtcpeer",
            name="client_peer_id",
            field=models.CharField(
                blank=True,
                help_text="Client-generated persistent ID for reconnection tracking",
                max_length=255,
                null=True,
            ),
        ),
    ]
