# Global exclusions for all hooks
exclude: |
  (?x)^(
    \.venv/.*|
    venv/.*|
    env/.*|
    \.env/.*|
    node_modules/.*|
    \.git/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    \.coverage.*|
    build/.*|
    dist/.*|
    \.idea/.*|
    \.vscode/.*|
    migrations/.*
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: '^tests/fixtures/.*\.sdrf\.tsv$'
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=120']

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=120']

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=160', '--extend-ignore=E203,W503,D100,D101,D102,D104,D105,D200,D202,D205,D400,D401,D106,E402,E501']
        additional_dependencies: [flake8-docstrings]
