# Generated by Django 5.2.6 on 2025-09-05 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="annotation_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("sketch", "Sketch"),
                    ("other", "Other"),
                    ("checklist", "Checklist"),
                    ("counter", "Counter"),
                    ("table", "Table"),
                    ("alignment", "Alignment"),
                    ("calculator", "Calculator"),
                    ("mcalculator", "Molarity Calculator"),
                    ("randomization", "Randomization"),
                    ("instrument", "Instrument"),
                    ("metadata", "Metadata"),
                    ("booking", "Booking"),
                ],
                default="text",
                help_text="Type of annotation content",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalannotation",
            name="annotation_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("sketch", "Sketch"),
                    ("other", "Other"),
                    ("checklist", "Checklist"),
                    ("counter", "Counter"),
                    ("table", "Table"),
                    ("alignment", "Alignment"),
                    ("calculator", "Calculator"),
                    ("mcalculator", "Molarity Calculator"),
                    ("randomization", "Randomization"),
                    ("instrument", "Instrument"),
                    ("metadata", "Metadata"),
                    ("booking", "Booking"),
                ],
                default="text",
                help_text="Type of annotation content",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AnnotationBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument_usage_id",
                    models.PositiveIntegerField(
                        help_text="ID of the InstrumentUsage booking this annotation is linked to"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation of type 'booking' linked to instrument usage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_links",
                        to="ccc.annotation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("annotation", "instrument_usage_id")},
            },
        ),
    ]
