# Generated by Django 5.2.6 on 2025-09-05 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0002_alter_annotation_annotation_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnnotationBooking",
        ),
    ]
