# Generated by Django 5.2.6 on 2025-10-06 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0003_delete_annotationbooking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLabGroupPermission",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "can_view",
                    models.BooleanField(
                        default=False,
                        help_text="Can view lab group details and members",
                    ),
                ),
                (
                    "can_invite",
                    models.BooleanField(
                        default=False,
                        help_text="Can invite new members to the lab group",
                    ),
                ),
                (
                    "can_manage",
                    models.BooleanField(
                        default=False,
                        help_text="Can modify lab group settings and manage permissions",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ccc.labgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical lab group permission",
                "verbose_name_plural": "historical lab group permissions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LabGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(
                        default=False,
                        help_text="Can view lab group details and members",
                    ),
                ),
                (
                    "can_invite",
                    models.BooleanField(
                        default=False,
                        help_text="Can invite new members to the lab group",
                    ),
                ),
                (
                    "can_manage",
                    models.BooleanField(
                        default=False,
                        help_text="Can modify lab group settings and manage permissions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_group_permissions",
                        to="ccc.labgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_group_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("user", "lab_group")},
            },
        ),
    ]
