# Generated by Django 5.2.6 on 2025-10-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0004_historicallabgrouppermission_labgrouppermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabgroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Parent lab group in the hierarchy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccc.labgroup",
            ),
        ),
        migrations.AddField(
            model_name="labgroup",
            name="parent_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent lab group in the hierarchy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_groups",
                to="ccc.labgroup",
            ),
        ),
    ]
