# Generated by Django 5.2.6 on 2025-10-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0005_historicallabgroup_parent_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabgrouppermission",
            name="can_process_jobs",
            field=models.BooleanField(default=False, help_text="Can be assigned to process instrument jobs"),
        ),
        migrations.AddField(
            model_name="labgrouppermission",
            name="can_process_jobs",
            field=models.BooleanField(default=False, help_text="Can be assigned to process instrument jobs"),
        ),
    ]
