# Generated by Django 5.2.6 on 2025-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0006_add_can_process_jobs_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabgroup",
            name="allow_process_jobs",
            field=models.BooleanField(
                default=False,
                help_text="Whether new members automatically get can_process_jobs permission",
            ),
        ),
        migrations.AddField(
            model_name="labgroup",
            name="allow_process_jobs",
            field=models.BooleanField(
                default=False,
                help_text="Whether new members automatically get can_process_jobs permission",
            ),
        ),
    ]
