# Generated by Django 5.2.6 on 2025-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0007_historicallabgroup_allow_process_jobs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="booking_deletion_window_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Time window (in minutes) after booking creation during which the creator can delete it. After this window, bookings become permanent and cannot be deleted by regular users. Staff and instrument managers can always delete bookings.",
            ),
        ),
    ]
