# Generated by Django 5.2.6 on 2025-10-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0008_siteconfig_booking_deletion_window_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="annotation_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("sketch", "Sketch"),
                    ("other", "Other"),
                    ("checklist", "Checklist"),
                    ("counter", "Counter"),
                    ("table", "Table"),
                    ("alignment", "Alignment"),
                    ("calculator", "Calculator"),
                    ("mcalculator", "Molarity Calculator"),
                    ("randomization", "Randomization"),
                    ("metadata", "Metadata"),
                    ("booking", "Booking"),
                ],
                default="text",
                help_text="Type of annotation content",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalannotation",
            name="annotation_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("sketch", "Sketch"),
                    ("other", "Other"),
                    ("checklist", "Checklist"),
                    ("counter", "Counter"),
                    ("table", "Table"),
                    ("alignment", "Alignment"),
                    ("calculator", "Calculator"),
                    ("mcalculator", "Molarity Calculator"),
                    ("randomization", "Randomization"),
                    ("metadata", "Metadata"),
                    ("booking", "Booking"),
                ],
                default="text",
                help_text="Type of annotation content",
                max_length=20,
            ),
        ),
    ]
