# Generated by Django 5.2.8 on 2025-11-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0010_move_asynctaskstatus_to_ccc"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="ui_features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="UI feature visibility configuration. Controls which features are shown in the frontend. Example: {'show_metadata_tables': true, 'show_protocols': false, 'show_instruments': true}. Default features: show_metadata_tables, show_instruments, show_sessions, show_protocols, show_messages, show_notifications, show_sample_management, show_webrtc. Admins can add custom feature flags as needed.",
            ),
        ),
    ]
