# Generated by Django 5.2.8 on 2025-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0011_siteconfig_ui_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="ui_features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="UI feature visibility configuration. Controls which features are shown in the frontend. Example: {'show_metadata_tables': true, 'show_protocols': false, 'show_instruments': true}. Default features: show_metadata_tables, show_instruments, show_sessions, show_protocols, show_messages, show_notifications, show_storage, show_webrtc, show_billing. Admins can add custom feature flags as needed.",
            ),
        ),
    ]
