# Generated by Django 5.2.8 on 2025-11-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0012_alter_siteconfig_ui_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="whisper_cpp_model",
            field=models.CharField(
                default="/app/whisper.cpp/models/ggml-medium.bin",
                help_text="Path to the default Whisper.cpp model file used for audio/video transcription. Common models: ggml-tiny.bin (75 MB), ggml-base.bin (142 MB), ggml-small.bin (466 MB), ggml-medium.bin (1.5 GB), ggml-large-v3.bin (3.1 GB). Larger models provide better accuracy but require more resources and take longer to process.",
                max_length=512,
            ),
        ),
    ]
