# Generated by Django 5.2.8 on 2025-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0013_siteconfig_whisper_cpp_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="cached_available_models",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cached list of available Whisper.cpp models reported by the transcribe worker. This is automatically updated by the transcribe worker on startup. Each model includes: path, name, size, size_bytes, and description.",
            ),
        ),
    ]
