# Generated by Django 5.2.11 on 2026-03-17 08:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0014_siteconfig_cached_available_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementCommandExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "command_name",
                    models.CharField(
                        choices=[
                            ("sync_schemas", "Sync Schemas"),
                            ("load_column_templates", "Load Column Templates"),
                            ("load_ontologies", "Load All Ontologies"),
                            ("load_species", "Load Species"),
                            ("load_tissue", "Load Tissue"),
                            ("load_human_disease", "Load Human Disease"),
                            ("load_subcellular_location", "Load Subcellular Location"),
                            ("load_ms_mod", "Load MS Modifications"),
                            ("load_ms_term", "Load MS Terms"),
                            (
                                "cleanup_expired_task_files",
                                "Cleanup Expired Task Files",
                            ),
                            ("check_workers", "Check Workers"),
                            ("cleanup_dead_workers", "Cleanup Dead Workers"),
                        ],
                        max_length=100,
                    ),
                ),
                ("command_args", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        help_text="RQ job ID for async execution",
                        max_length=100,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="command_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Management Command Execution",
                "verbose_name_plural": "Management Command Executions",
                "ordering": ["-created_at"],
            },
        ),
    ]
