# Generated by Django 6.0.5 on 2026-05-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0017_add_device_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("manifest_cache", models.JSONField(default=dict)),
                ("base_url", models.URLField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
    ]
