# Generated by Django 6.0.5 on 2026-05-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0018_add_plugin_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("installing", "Installing"),
                    ("starting", "Starting"),
                    ("running", "Running"),
                    ("stopped", "Stopped"),
                    ("error", "Error"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plugin",
            name="progress_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="plugin",
            name="progress_message",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="plugin",
            name="token",
            field=models.CharField(db_index=True, default="", max_length=64, unique=True),
        ),
    ]
