"""
Django settings for cupcake_vanilla project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-%!ai*=3sq=w)=qpv72559p=o*v6jfk$@bb0&0(t^4drjmv-7ol")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# CUPCAKE Configuration
# Enable individual CUPCAKE apps based on requirements
ENABLE_CUPCAKE_MACARON = os.environ.get("ENABLE_CUPCAKE_MACARON", "True").lower() == "true"
ENABLE_CUPCAKE_MINT_CHOCOLATE = os.environ.get("ENABLE_CUPCAKE_MINT_CHOCOLATE", "False").lower() == "true"
ENABLE_CUPCAKE_SALTED_CARAMEL = os.environ.get("ENABLE_CUPCAKE_SALTED_CARAMEL", "True").lower() == "true"
ENABLE_CUPCAKE_RED_VELVET = os.environ.get("ENABLE_CUPCAKE_RED_VELVET", "True").lower() == "true"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "simple_history",
    "drf_chunked_upload",
    "social_django",
    "channels",
    "django_rq",
    "ccc.apps.CccConfig",
    "ccv.apps.CcvConfig",
]

# Conditionally add CUPCAKE apps based on configuration
if ENABLE_CUPCAKE_MACARON:
    INSTALLED_APPS.append("ccm.apps.CcmConfig")

if ENABLE_CUPCAKE_MINT_CHOCOLATE:
    INSTALLED_APPS.append("ccmc.apps.CcmcConfig")

if ENABLE_CUPCAKE_SALTED_CARAMEL:
    INSTALLED_APPS.append("ccsc.apps.CcscConfig")

if ENABLE_CUPCAKE_RED_VELVET:
    INSTALLED_APPS.append("ccrv.apps.CcrvConfig")

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "cupcake_vanilla.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cupcake_vanilla.wsgi.application"
ASGI_APPLICATION = "cupcake_vanilla.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "cupcake_vanilla_db"),
        "USER": os.environ.get("POSTGRES_USER", "cupcake_vanilla"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "cupcake_vanilla_pass"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Cache configuration
# https://docs.djangoproject.com/en/5.2/topics/cache/

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "retry_on_timeout": True,
                "socket_keepalive": True,
                "socket_keepalive_options": {},
            },
        },
        "KEY_PREFIX": "cupcake_vanilla",
        "VERSION": 1,
        "TIMEOUT": 300,  # 5 minutes default timeout
    }
}

# Session cache
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Cache time to live is 15 minutes by default
CACHE_TTL = 60 * 15

# RQ (Redis Queue) configuration
RQ_QUEUES = {
    "default": {
        "HOST": os.environ.get("REDIS_HOST", "127.0.0.1"),
        "PORT": int(os.environ.get("REDIS_PORT", "6379")),
        "DB": int(os.environ.get("REDIS_DB_RQ", "3")),  # Use different DB from cache and channels
        "PASSWORD": os.environ.get("REDIS_PASSWORD", None),
        "DEFAULT_TIMEOUT": 3600,  # 1 hour timeout for tasks
        "CONNECTION_KWARGS": {
            "health_check_interval": 30,
        },
    },
    "high": {
        "HOST": os.environ.get("REDIS_HOST", "127.0.0.1"),
        "PORT": int(os.environ.get("REDIS_PORT", "6379")),
        "DB": int(os.environ.get("REDIS_DB_RQ", "3")),
        "PASSWORD": os.environ.get("REDIS_PASSWORD", None),
        "DEFAULT_TIMEOUT": 1800,  # 30 minutes for high priority tasks
        "CONNECTION_KWARGS": {
            "health_check_interval": 30,
        },
    },
    "low": {
        "HOST": os.environ.get("REDIS_HOST", "127.0.0.1"),
        "PORT": int(os.environ.get("REDIS_PORT", "6379")),
        "DB": int(os.environ.get("REDIS_DB_RQ", "3")),
        "PASSWORD": os.environ.get("REDIS_PASSWORD", None),
        "DEFAULT_TIMEOUT": 7200,  # 2 hours for low priority tasks
        "CONNECTION_KWARGS": {
            "health_check_interval": 30,
        },
    },
    "transcribe": {
        "HOST": os.environ.get("REDIS_HOST", "127.0.0.1"),
        "PORT": int(os.environ.get("REDIS_PORT", "6379")),
        "DB": int(os.environ.get("REDIS_DB_RQ", "3")),
        "PASSWORD": os.environ.get("REDIS_PASSWORD", None),
        "DEFAULT_TIMEOUT": 3600,  # 1 hour for transcription tasks
        "CONNECTION_KWARGS": {
            "health_check_interval": 30,
        },
    },
}


# Task result file settings
TASK_RESULT_EXPIRE_DAYS = int(os.environ.get("TASK_RESULT_EXPIRE_DAYS", "7"))  # Files expire after 7 days
TASK_DOWNLOAD_TOKEN_MAX_AGE = int(os.environ.get("TASK_DOWNLOAD_TOKEN_MAX_AGE", "600"))  # 10 minutes

PROTOCOLS_IO_ACCESS_TOKEN = os.environ.get("PROTOCOLS_IO_ACCESS_TOKEN", "")

# Django Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/2")],
            "capacity": 1500,  # Maximum number of messages to store
            "expiry": 60,  # Message expiry time in seconds
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 50,
}

# CORS configuration

CORS_EXPOSED_HEADERS = ["Set-Cookie"]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "withCredentials",
    "http_x_xsrf_token",
    "content-range",
    "content-disposition",
    "x-cupcake-ccv-instance-id",
    "http_x_cupcake_ccv_instance_id",
    "http-x-session-token",
    "http-x-csrftoken",
    "x-session-token",
]
CSRF_COOKIE_NAME = "csrfToken"
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

cors_origins = os.environ.get("CORS_ORIGIN_WHITELIST", "http://localhost:4200").split(",")

cors_origins = [origin.strip() for origin in cors_origins if origin.strip()]
cors_origins = list(dict.fromkeys(cors_origins))

CSRF_TRUSTED_ORIGINS = cors_origins
CORS_ORIGIN_WHITELIST = cors_origins
CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost").split(",")

# Simple JWT configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

JWT_REMEMBER_ME_ACCESS_TOKEN_LIFETIME = timedelta(hours=24)
JWT_REMEMBER_ME_REFRESH_TOKEN_LIFETIME = timedelta(days=30)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB

# Media files (backend uploads)
MEDIA_URL = "/api/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Chunked upload settings
DRF_CHUNKED_UPLOAD_PATH = "chunked_uploads"
DRF_CHUNKED_UPLOAD_ABSTRACT_MODEL = False
DRF_CHUNKED_UPLOAD_MAX_BYTES = 1024 * 1024 * 1024 * 2  # 2GB
DRF_CHUNKED_UPLOAD_USER_RESTRICTED = True  # Restrict uploads to authenticated users
DRF_CHUNKED_UPLOAD_COMPLETE_EXT = ".done"
DRF_CHUNKED_UPLOAD_INCOMPLETE_EXT = ".part"
DRF_CHUNKED_UPLOAD_CHECKSUM = "sha256"  # Use SHA-256 for file hashing

# Authentication backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Default Django auth
    "ccc.auth_backends.ORCIDOAuth2Backend",  # Custom ORCID OAuth backend
]

# ORCID OAuth2 Configuration
ORCID_CLIENT_ID = os.environ.get("ORCID_CLIENT_ID", "")
ORCID_CLIENT_SECRET = os.environ.get("ORCID_CLIENT_SECRET", "")
ORCID_BASE_URL = os.environ.get("ORCID_BASE_URL", "https://sandbox.orcid.org")  # Use sandbox by default

# Social Auth Configuration (backup/alternative approach)
SOCIAL_AUTH_ORCID_KEY = ORCID_CLIENT_ID
SOCIAL_AUTH_ORCID_SECRET = ORCID_CLIENT_SECRET
SOCIAL_AUTH_ORCID_SANDBOX = ORCID_BASE_URL == "https://sandbox.orcid.org"

# User creation settings
SOCIAL_AUTH_CREATE_USERS = True
SOCIAL_AUTH_UPDATE_USER_DATA = True
SOCIAL_AUTH_USER_MODEL = "auth.User"

# Logging configuration for OAuth
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "ccc.auth_backends": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

# Whisper.cpp configuration for transcription
WHISPERCPP_PATH = os.environ.get("WHISPERCPP_PATH", "/app/whisper.cpp/build/bin/whisper-cli")
WHISPERCPP_DEFAULT_MODEL = os.environ.get("WHISPERCPP_DEFAULT_MODEL", "/app/whisper.cpp/models/ggml-medium.bin")
WHISPERCPP_THREAD_COUNT = os.environ.get("WHISPERCPP_THREAD_COUNT", "6")

# Feature flags
USE_WHISPER = os.environ.get("USE_WHISPER", "False") == "True"
