# Generated by Django 5.2.6 on 2025-09-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmetadatacolumn",
            name="enable_typeahead",
            field=models.BooleanField(default=True, help_text="Enable typeahead suggestions in forms"),
        ),
        migrations.AddField(
            model_name="metadatacolumn",
            name="enable_typeahead",
            field=models.BooleanField(default=True, help_text="Enable typeahead suggestions in forms"),
        ),
        migrations.AlterField(
            model_name="historicalmetadatacolumntemplate",
            name="ontology_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("species", "Species"),
                    ("tissue", "Tissue"),
                    ("human_disease", "Human Disease"),
                    ("subcellular_location", "Subcellular Location"),
                    ("ms_unique_vocabularies", "MS Unique Vocabularies"),
                    ("unimod", "Unimod Modifications"),
                    ("ncbi_taxonomy", "NCBI Taxonomy"),
                    ("mondo", "MONDO Disease"),
                    ("uberon", "UBERON Anatomy"),
                    ("chebi", "ChEBI"),
                    ("cell_ontology", "Cell Ontology"),
                    ("psi_ms", "PSI-MS Controlled Vocabulary"),
                ],
                help_text="Type of ontology to use for validation and suggestions",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metadatacolumntemplate",
            name="ontology_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("species", "Species"),
                    ("tissue", "Tissue"),
                    ("human_disease", "Human Disease"),
                    ("subcellular_location", "Subcellular Location"),
                    ("ms_unique_vocabularies", "MS Unique Vocabularies"),
                    ("unimod", "Unimod Modifications"),
                    ("ncbi_taxonomy", "NCBI Taxonomy"),
                    ("mondo", "MONDO Disease"),
                    ("uberon", "UBERON Anatomy"),
                    ("chebi", "ChEBI"),
                    ("cell_ontology", "Cell Ontology"),
                    ("psi_ms", "PSI-MS Controlled Vocabulary"),
                ],
                help_text="Type of ontology to use for validation and suggestions",
                max_length=50,
                null=True,
            ),
        ),
    ]
