# Generated by Django 5.2.5 on 2025-08-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmetadatatabletemplate",
            name="_force_migration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="metadatatabletemplate",
            name="_force_migration",
            field=models.BooleanField(default=False),
        ),
    ]
