# Generated by Django 5.2.6 on 2025-09-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccv", "0002_historicalmetadatacolumn_enable_typeahead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynctaskstatus",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("EXPORT_EXCEL", "Export Excel Template"),
                    ("EXPORT_SDRF", "Export SDRF File"),
                    ("IMPORT_SDRF", "Import SDRF File"),
                    ("IMPORT_EXCEL", "Import Excel File"),
                    ("EXPORT_MULTIPLE_SDRF", "Export Multiple SDRF Files"),
                    ("EXPORT_MULTIPLE_EXCEL", "Export Multiple Excel Templates"),
                    ("VALIDATE_TABLE", "Validate Metadata Table"),
                    ("REORDER_TABLE_COLUMNS", "Reorder Table Columns"),
                    ("REORDER_TEMPLATE_COLUMNS", "Reorder Template Columns"),
                ],
                max_length=25,
            ),
        ),
    ]
