# Generated by Django 5.2.5 on 2025-08-23 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ccv", "0002_historicalmetadatatabletemplate__force_migration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmetadatatabletemplate",
            name="_force_migration",
        ),
        migrations.RemoveField(
            model_name="metadatatabletemplate",
            name="_force_migration",
        ),
    ]
