# Generated by Django 5.2.6 on 2025-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccv", "0003_alter_asynctaskstatus_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmetadatacolumn",
            name="not_available",
            field=models.BooleanField(
                default=False,
                help_text="Whether this column is marked as not available",
            ),
        ),
        migrations.AddField(
            model_name="historicalmetadatacolumntemplate",
            name="not_applicable",
            field=models.BooleanField(
                default=False,
                help_text="Whether this column is marked as not applicable by default",
            ),
        ),
        migrations.AddField(
            model_name="historicalmetadatacolumntemplate",
            name="not_available",
            field=models.BooleanField(
                default=False,
                help_text="Whether this column is marked as not available by default",
            ),
        ),
        migrations.AddField(
            model_name="metadatacolumn",
            name="not_available",
            field=models.BooleanField(
                default=False,
                help_text="Whether this column is marked as not available",
            ),
        ),
        migrations.AddField(
            model_name="metadatacolumntemplate",
            name="not_applicable",
            field=models.BooleanField(
                default=False,
                help_text="Whether this column is marked as not applicable by default",
            ),
        ),
        migrations.AddField(
            model_name="metadatacolumntemplate",
            name="not_available",
            field=models.BooleanField(
                default=False,
                help_text="Whether this column is marked as not available by default",
            ),
        ),
    ]
