# Generated by Django 5.2.6 on 2025-11-05 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ccv", "0005_alter_asynctaskstatus_task_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskresult",
            name="task",
        ),
        migrations.DeleteModel(
            name="AsyncTaskStatus",
        ),
        migrations.DeleteModel(
            name="TaskResult",
        ),
    ]
