# Generated by Django 5.2.11 on 2026-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccv", "0009_metadatacolumntemplate_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmetadatacolumntemplate",
            name="input_type",
            field=models.CharField(
                blank=True,
                default="text",
                help_text="Input type hint for frontend rendering (text, select, number_with_unit, pattern, ontology)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalmetadatacolumntemplate",
            name="units",
            field=models.JSONField(
                blank=True, default=list, help_text="List of valid units for number_with_unit input type"
            ),
        ),
        migrations.AddField(
            model_name="historicalmetadatacolumntemplate",
            name="validators",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of validators from sdrf-pipelines schema with their configurations",
            ),
        ),
    ]
