# Generated by Django 6.0.3 on 2026-04-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccv", "0010_historicalmetadatacolumntemplate_input_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BTOTerm",
            fields=[
                ("identifier", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("definition", models.TextField(blank=True, null=True)),
                ("synonyms", models.TextField(blank=True, null=True)),
                ("xrefs", models.TextField(blank=True, null=True)),
                ("parent_terms", models.TextField(blank=True, null=True)),
                ("part_of", models.TextField(blank=True, null=True)),
                ("obsolete", models.BooleanField(default=False)),
                ("replacement_term", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "BTO Term",
                "verbose_name_plural": "BTO Terms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiseaseOntologyTerm",
            fields=[
                ("identifier", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("definition", models.TextField(blank=True, null=True)),
                ("synonyms", models.TextField(blank=True, null=True)),
                ("xrefs", models.TextField(blank=True, null=True)),
                ("parent_terms", models.TextField(blank=True, null=True)),
                ("obsolete", models.BooleanField(default=False)),
                ("replacement_term", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Disease Ontology Term",
                "verbose_name_plural": "Disease Ontology Terms",
                "ordering": ["name"],
            },
        ),
    ]
