FROM python:3.11-bookworm
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg > /dev/null
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
RUN apt-get update
RUN apt-get -y install postgresql-client-15

ARG TARGETARCH
ENV SUPERCRONIC_VERSION=v0.2.33

RUN if [ -z "${TARGETARCH}" ]; then export TARGETARCH="amd64"; fi && \
    case "${TARGETARCH}" in \
    "amd64") \
        export SUPERCRONIC_ARCH="linux-amd64" && \
        export SUPERCRONIC_SHA1SUM="71b0d58cc53f6bd72cf2f293e09e294b79c666d8" ;; \
    "arm64") \
        export SUPERCRONIC_ARCH="linux-arm64" && \
        export SUPERCRONIC_SHA1SUM="73ddda42a9ad1adf21c0a6e52b8a48dbc24b1ea8" ;; \
    *) \
        echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    export SUPERCRONIC_URL="https://github.com/aptible/supercronic/releases/download/${SUPERCRONIC_VERSION}/supercronic-${SUPERCRONIC_ARCH}" && \
    export SUPERCRONIC="supercronic-${SUPERCRONIC_ARCH}" && \
    curl -fsSLO "$SUPERCRONIC_URL" && \
    echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - && \
    chmod +x "$SUPERCRONIC" && \
    mv "$SUPERCRONIC" "/usr/local/bin/supercronic"

WORKDIR /app
RUN mkdir -p "/app/media" "/app/media/temp" "/app/staticfiles"

# Install Poetry
RUN pip install --upgrade pip && pip install poetry
RUN poetry config virtualenvs.create false

# Copy application code
COPY . /app/

# Install dependencies and project
RUN poetry lock
RUN poetry install --only=main

CMD ["python", "manage.py", "rqworker", "default", "high", "low", "transcribe", "--with-scheduler"]
