FROM nginx:alpine

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Create webroot for ACME challenges
RUN mkdir -p /var/www/certbot && chown -R nginx:nginx /var/www/certbot

# Copy site-specific configuration
COPY ./nginx-conf/ccv.ome.quest.conf /etc/nginx/conf.d/ccv.ome.quest.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
