# Generated by Django 5.2.6 on 2025-09-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0001_initial"),
        ("ccrv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of annotations within the session",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation attached to this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_attachments",
                        to="ccc.annotation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session this annotation is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_annotations",
                        to="ccrv.session",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("session", "annotation")},
            },
        ),
        migrations.CreateModel(
            name="SessionAnnotationFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of folders within the session",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="Annotation folder attached to this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_attachments",
                        to="ccc.annotationfolder",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session this folder belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_annotation_folders",
                        to="ccrv.session",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("session", "folder")},
            },
        ),
        migrations.CreateModel(
            name="StepAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of annotations within the step",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation attached to this step",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_attachments",
                        to="ccc.annotation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session context for this step annotation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_annotations",
                        to="ccrv.session",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="Protocol step this annotation is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_annotations",
                        to="ccrv.protocolstep",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("session", "step", "annotation")},
            },
        ),
    ]
