# Generated by Django 5.2.6 on 2025-09-05 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0004_historicalinstrumentpermission_instrumentpermission"),
        ("ccrv", "0002_sessionannotation_sessionannotationfolder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentUsageSessionAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of session annotations within the instrument usage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument_usage",
                    models.ForeignKey(
                        help_text="Instrument usage booking this session annotation is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_annotation_links",
                        to="ccm.instrumentusage",
                    ),
                ),
                (
                    "session_annotation",
                    models.ForeignKey(
                        help_text="Session annotation linked to instrument usage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_usage_links",
                        to="ccrv.sessionannotation",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("session_annotation", "instrument_usage")},
            },
        ),
    ]
