# Generated by Django 5.2.6 on 2025-09-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccrv", "0003_instrumentusagesessionannotation"),
        ("ccv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionannotation",
            name="metadata_table",
            field=models.OneToOneField(
                blank=True,
                help_text="Metadata table for experimental data associated with this session annotation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_annotation",
                to="ccv.metadatatable",
            ),
        ),
    ]
