# Generated by Django 5.2.6 on 2025-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccrv", "0004_sessionannotation_metadata_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltimekeeper",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="timekeeper",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
