# Generated by Django 5.2.6 on 2025-10-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccrv", "0005_historicaltimekeeper_name_timekeeper_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltimekeeper",
            name="original_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Original/target duration in seconds for reset functionality",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="timekeeper",
            name="original_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Original/target duration in seconds for reset functionality",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TimeKeeperEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("stopped", "Stopped"),
                            ("reset", "Reset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_time", models.DateTimeField(auto_now_add=True)),
                (
                    "duration_at_event",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in seconds at time of event",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "time_keeper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ccrv.timekeeper",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_time"],
            },
        ),
    ]
