# Generated by Django 5.2.7 on 2025-10-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccrv", "0006_historicaltimekeeper_original_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltimekeeper",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timekeeper",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
