# Generated by Django 5.2.6 on 2025-10-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0007_historicalinstrument_allow_overlapping_bookings_and_more"),
        ("ccrv", "0007_alter_historicaltimekeeper_start_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentUsageStepAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of step annotations within the instrument usage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument_usage",
                    models.ForeignKey(
                        help_text="Instrument usage booking this step annotation is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_annotation_links",
                        to="ccm.instrumentusage",
                    ),
                ),
                (
                    "step_annotation",
                    models.ForeignKey(
                        help_text="Step annotation linked to instrument usage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_usage_links",
                        to="ccrv.stepannotation",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("step_annotation", "instrument_usage")},
            },
        ),
    ]
