# Generated by Django 5.2.8 on 2025-11-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccmc", "0003_remove_historicalwebrtcsession_thread_and_more"),
        ("ccrv", "0008_instrumentusagestepannotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="webrtc_sessions",
            field=models.ManyToManyField(blank=True, related_name="ccrv_sessions", to="ccmc.webrtcsession"),
        ),
    ]
