# Generated by Django 6.0.5 on 2026-07-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccrv", "0009_session_webrtc_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstepvariation",
            name="session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccrv.session",
            ),
        ),
        migrations.AddField(
            model_name="stepvariation",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_variations",
                to="ccrv.session",
            ),
        ),
    ]
