# Generated by Django 5.2.6 on 2025-09-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0001_initial"),
        ("ccm", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of annotations within the folder",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation attached to this instrument",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_attachments",
                        to="ccc.annotation",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="Folder (Manuals, Certificates, or Maintenance) containing this annotation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_annotations",
                        to="ccc.annotationfolder",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        help_text="Instrument this annotation is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_annotations",
                        to="ccm.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("instrument", "annotation", "folder")},
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLogAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of annotations within the maintenance log",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation attached to this maintenance log",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_log_attachments",
                        to="ccc.annotation",
                    ),
                ),
                (
                    "maintenance_log",
                    models.ForeignKey(
                        help_text="MaintenanceLog this annotation is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_log_annotations",
                        to="ccm.maintenancelog",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("maintenance_log", "annotation")},
            },
        ),
        migrations.CreateModel(
            name="StoredReagentAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of annotations within the folder",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation attached to this stored reagent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_reagent_attachments",
                        to="ccc.annotation",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="Folder (MSDS, Certificates, or Manuals) containing this annotation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_reagent_annotations",
                        to="ccc.annotationfolder",
                    ),
                ),
                (
                    "stored_reagent",
                    models.ForeignKey(
                        help_text="StoredReagent this annotation is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_reagent_annotations",
                        to="ccm.storedreagent",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("stored_reagent", "annotation", "folder")},
            },
        ),
    ]
