# Generated by Django 5.2.6 on 2025-10-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0006_add_can_process_jobs_permission"),
        ("ccm", "0004_historicalinstrumentpermission_instrumentpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinstrumentjob",
            name="lab_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Lab group responsible for processing this job",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccc.labgroup",
            ),
        ),
        migrations.AddField(
            model_name="instrumentjob",
            name="lab_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Lab group responsible for processing this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instrument_jobs",
                to="ccc.labgroup",
            ),
        ),
    ]
