# Generated by Django 5.2.6 on 2025-10-17 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0005_historicalinstrumentjob_lab_group_and_more"),
        ("ccv", "0003_alter_asynctaskstatus_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcontact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="externalcontact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="externalcontactdetails",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="externalcontactdetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="historicalexternalcontact",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalexternalcontact",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalexternalcontactdetails",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalexternalcontactdetails",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalinstrument",
            name="metadata_table",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Metadata table storing instrument specifications that jobs can reference",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccv.metadatatable",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstoredreagent",
            name="metadata_table",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Metadata table storing reagent specifications and properties",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccv.metadatatable",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="metadata_table",
            field=models.OneToOneField(
                blank=True,
                help_text="Metadata table storing instrument specifications that jobs can reference",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instrument",
                to="ccv.metadatatable",
            ),
        ),
        migrations.AlterField(
            model_name="storedreagent",
            name="metadata_table",
            field=models.OneToOneField(
                blank=True,
                help_text="Metadata table storing reagent specifications and properties",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_reagent",
                to="ccv.metadatatable",
            ),
        ),
    ]
