# Generated by Django 5.2.7 on 2025-10-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0006_externalcontact_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinstrument",
            name="allow_overlapping_bookings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instrument",
            name="allow_overlapping_bookings",
            field=models.BooleanField(default=False),
        ),
    ]
