# Generated by Django 5.2.6 on 2025-10-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0007_historicalinstrument_allow_overlapping_bookings_and_more"),
        ("ccrv", "0008_instrumentusagestepannotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreagentaction",
            name="session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccrv.session",
            ),
        ),
        migrations.AddField(
            model_name="historicalreagentaction",
            name="step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccrv.protocolstep",
            ),
        ),
        migrations.AddField(
            model_name="reagentaction",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reagent_actions",
                to="ccrv.session",
            ),
        ),
        migrations.AddField(
            model_name="reagentaction",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reagent_actions",
                to="ccrv.protocolstep",
            ),
        ),
    ]
