# Generated by Django 5.2.6 on 2025-10-27 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0008_historicalreagentaction_session_and_more"),
        ("ccrv", "0008_instrumentusagestepannotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinstrumentjob",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Project this instrument job is associated with",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccrv.project",
            ),
        ),
        migrations.AddField(
            model_name="instrumentjob",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this instrument job is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instrument_jobs",
                to="ccrv.project",
            ),
        ),
    ]
