# Generated by Django 5.2.6 on 2025-10-28 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0009_historicalinstrumentjob_project_and_more"),
        ("ccv", "0003_alter_asynctaskstatus_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinstrumentjob",
            name="metadata_table_template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Template selected for creating metadata table for this job",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ccv.metadatatabletemplate",
            ),
        ),
        migrations.AddField(
            model_name="instrumentjob",
            name="metadata_table_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template selected for creating metadata table for this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instrument_jobs",
                to="ccv.metadatatabletemplate",
            ),
        ),
    ]
