# Generated by Django 5.2.6 on 2025-10-30 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccc", "0008_siteconfig_booking_deletion_window_minutes"),
        ("ccm", "0010_historicalinstrumentjob_metadata_table_template_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentjob",
            name="staff_annotations",
        ),
        migrations.RemoveField(
            model_name="instrumentjob",
            name="user_annotations",
        ),
        migrations.CreateModel(
            name="InstrumentJobAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of annotations within the job",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="Annotation attached to this instrument job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_job_attachments",
                        to="ccc.annotation",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Folder containing this annotation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instrument_job_annotations",
                        to="ccc.annotationfolder",
                    ),
                ),
                (
                    "instrument_job",
                    models.ForeignKey(
                        help_text="InstrumentJob this annotation is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_job_annotations",
                        to="ccm.instrumentjob",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("instrument_job", "annotation")},
            },
        ),
    ]
