# Generated by Django 5.2.6 on 2025-11-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0011_remove_instrumentjob_staff_annotations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentUsageJobAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of job annotations within the instrument usage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument_job_annotation",
                    models.ForeignKey(
                        help_text="Instrument job annotation linked to instrument usage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_usage_links",
                        to="ccm.instrumentjobannotation",
                    ),
                ),
                (
                    "instrument_usage",
                    models.ForeignKey(
                        help_text="Instrument usage booking this job annotation is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_annotation_links",
                        to="ccm.instrumentusage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("instrument_job_annotation", "instrument_usage")},
            },
        ),
    ]
