# Generated by Django 5.2.6 on 2025-11-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0012_instrumentusagejobannotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentjobannotation",
            name="role",
            field=models.CharField(
                choices=[("user", "Job Owner"), ("staff", "Assigned Staff")],
                default="user",
                help_text="Role in which this annotation was created: 'user' for job owner, 'staff' for assigned staff",
                max_length=10,
            ),
        ),
    ]
