# Generated by Django 5.2.8 on 2025-11-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccm", "0013_instrumentjobannotation_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstoredreagent",
            name="molecular_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Molecular weight in g/mol",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storedreagent",
            name="molecular_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Molecular weight in g/mol",
                max_digits=10,
                null=True,
            ),
        ),
    ]
